//
// ProviderStatusResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct ProviderStatusResponse: Codable {
    public var providerStatusList: [InsuranceProvider]

    public init(providerStatusList: [InsuranceProvider]) {
        self.providerStatusList = providerStatusList
    }

}

