//
// ProviderStatusResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProviderStatusResponse: Codable {

    public var providerStatusList: [ProviderStatus]?

    public init(providerStatusList: [ProviderStatus]?) {
        self.providerStatusList = providerStatusList
    }


}

