//
// IntegrateInsuranceResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct IntegrateInsuranceResponse: Codable {

    public var optionalAutoStartToken: String?
    public var scrapeSessionId: UUID

    public init(optionalAutoStartToken: String?, scrapeSessionId: UUID) {
        self.optionalAutoStartToken = optionalAutoStartToken
        self.scrapeSessionId = scrapeSessionId
    }


}

